apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams-client
  labels:
    app: streams-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streams-client
  template:
    metadata:
      labels:
        app: streams-client
    spec:
      containers:
      - name: streams-client
        image: streams-client:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: streams-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
